LogisticRegression:
  max_iter: 1000

RandomForestClassifier:
  criterion: 'entropy'
  max_depth: 3
  max_features: 'log2'
  min_samples_leaf: 1
  min_samples_split: 2
  n_estimators: 1000

XGBClassifier:
  colsample_bytree: 0.7
  learning_rate: 0.1
  max_depth: 5
  n_estimators: 200
  subsample: 0.9